name: auth_app
description: "A new Flutter project."
publish_to: "none"
version: 0.9.9+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  provider:
  shared_preferences:
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.0
  xml: ^6.5.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^14.0.1
  sliding_up_panel: ^2.0.0
  flutter_dotenv:
  mapbox_maps_flutter:
  path_provider:
  drag_and_drop_lists: ^0.4.2
  sunrise_sunset_calc: 
  shimmer: ^3.0.0
  timelines_plus: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  google_nav_bar: ^5.0.7

flutter:
  uses-material-design: true

  assets:
    - config.env
    - assets/images/
    # - assets/campus_buildings.json
    # - assets/campus_buildings_centroids.json
    - assets/icons/building.png
    - assets/icons/cafe.png
    - assets/icons/gym.png
    - assets/icons/default.png
    - assets/icons/destination.png
    - assets/icons/favourite.png
    - assets/icons/library.png
    - assets/icons/mensa.png



    # Custom public transport icon
    - assets/icons/public_transport.svg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/android_app_icon.png" # fallback for older devices
  adaptive_icon_background: "assets/images/tubify_logo_background.png"
  adaptive_icon_foreground: "assets/images/tubify_logo_white_overlay_compact.png"
