name: auth_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.0
  xml: ^6.5.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^14.0.1
  sliding_up_panel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  google_nav_bar: ^5.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/campus_buildings.json
    # - assets/campus_buildings_centroids.json
    - assets/sample_mensa_menu.json
    - assets/icons/pin_mensa.png
    - assets/icons/pin_cafe.png
    - assets/icons/pin_library.png
    - assets/icons/pin_default.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
  

flutter_icons:
  android: true
  ios: false # Leave iOS unchanged
  image_path: "assets/images/android_app_icon.png" # Path to your app icon

